title:        "@tmm1"
tagline:      "computer talk by @tmm1"
url:          http://tmm1.net
author:
  name:       "Aman Gupta"
  email:      "aman@tmm1.net"
markdown:     redcarpet
permalink:    /:title
pygments:     true
paginate:     5
